//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDependency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation_Detail
    {
        public int CD_ID { get; set; }
        public Nullable<int> AccountSend { get; set; }
        public Nullable<int> Conversation_ID { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public string Content { get; set; }
    }
}
